### ISSUE TITLE
Name of fonts should be in variable as well, like "Open Sans", Ubuntu...

### ISSUE THREAD

**Issue by rudnitskih** [IgnatSemchuk/elena-landing#5]

**Comment by IgnatSemchuk** [comment]
I dont understand issue

**Comment by rudnitskih** [comment]
```css
:root {
  --main-font: "PT Sans", sans-serif;
}
```
